name: KITS AB

exclude: [.editorconfig, .gitignore, Gemfile, Gemfile.lock, LICENSE.md, README.md]
permalink: pretty
relative_permalinks: false
timezone: Europe/Stockholm
url: http://www.kits.se

markdown: kramdown
kramdown:
  auto_ids: false
  enable_coderay: false
  entity_output: as_char
  footnote_nr: 1
  input: GFM
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6
  syntax_highlighter_opts:
    disable : true

collections:
  erbjudanden:
    output: false
  formaner:
    output: false
  jobb:
    output: true
    permalink: /jobb/:path/
  medarbetare:
    output: true
    permalink: /om/:path/
  projekt:
    output: false

defaults:
  -
    scope:
      path: ""
      type: erbjudanden
    values:
      layout: erbjudanden
  -
    scope:
      path: ""
      type: jobb
    values:
      layout: jobb
  -
    scope:
      path: ""
      type: medarbetare
    values:
      layout: medarbetare
  -
    scope:
      path: "blogg"
      type: posts
    values:
      layout: bloggpost
      categories: blogg
  -
    scope:
      path: "nyheter"
      type: posts
    values:
      layout: nyhet
      categories: nyheter

prose:
  relativeLinks: 'http://www.kits.se/api/prose/links.jsonp'
  ignore:
    - _includes
    - _layouts
    - _sass
    - api
    - css
    - js
    - .editorconfig
    - .gitignore
    - _config.yml
    - blogg.xml
    - Gemfile
    - Gemfile.lock
    - LICENSE.md
    - nyheter.xml
    - README.md
    - robots.txt
    - sitemap.xml
  metadata:
    "":
      - name: "layout"
        field:
          element: "hidden"
          value: "index"
      - name: "heading"
        field:
          element: "text"
          label: "Rubrik"
      - name: "page_title"
        field:
          element: "text"
          label: "Titel på sidan (om annan än Rubrik)"
      - name: "intro"
        field:
          element: "text"
          label: "Ingress"
      - name: "description"
        field:
          element: "text"
          label: "Text som visas i social medier"
    _erbjudanden:
      - name: "heading"
        field:
          element: "text"
          label: "Rubrik"
      - name: "image"
        field:
          element: "text"
          label: "Bild"
          help: "Namnet (utan .png) på den bild som ska användas för erbjudandet (som ska ligga som /images/erbjudanden/*)"
      - name: "index"
        field:
          element: "text"
          label: "Sorteringsindex (1 kommer först)"
    _formaner:
      - name: "heading"
        field:
          element: "text"
          label: "Rubrik"
      - name: "index"
        field:
          element: "text"
          label: "Sorteringsindex (1 kommer först)"
    _jobb:
      - name: "uid"
        field:
          element: "text"
          label: "Jobb ID"
          help: "Jobb ID används för att identifiera jobbet"
      - name: "heading"
        field:
          element: "text"
          label: "Rubrik"
      - name: "intro"
        field:
          element: "text"
          label: "Ingress"
      - name: "image"
        field:
          element: "select"
          label: "Bild"
          help: "Namnet på den bild som ska användas för jobbet (som ska ligga som /images/jobb/*)"
          options:
            - name: "person1"
              value: "person1"
            - name: "person2"
              value: "person2"
            - name: "person3"
              value: "person3"
            - name: "person4"
              value: "person4"
            - name: "person5"
              value: "person5"
            - name: "person6"
              value: "person6"
            - name: "person7"
              value: "person7"
            - name: "person8"
              value: "person8"
      - name: "index"
        field:
          element: "text"
          label: "Sorteringsindex (1 kommer först)"
    _medarbetare:
      - name: "uid"
        field:
          element: "text"
          label: "Medarbetar ID"
          help: "Medarbetar ID används för att identifiera personen"
          placeholder: "fornamnefternamn"
      - name: "image"
        field:
          element: "text"
          label: "Bild"
          help: "Namnet (utan .png och .jpg) på den bild som ska användas för personen (som ska ligga som /images/medarbetare/*)"
      - name: "name"
        field:
          element: "text"
          label: "Namn"
      - name: "email"
        field:
          element: "text"
          label: "E-post"
          placeholder: "fornamn.efternamn@kits.se"
      - name: "phone"
        field:
          element: "text"
          label: "Telefon"
          placeholder: "0708 – 12 34 56"
      - name: "twitter"
        field:
          element: "text"
          label: "Twitter"
          help: "Kan vara tom"
          placeholder: "fornamnefternamn"
      - name: "linkedin"
        field:
          element: "text"
          label: "LinkedIn"
          help: "Kan vara tom"
          placeholder: "https://se.linkedin.com/in/fornamnefternamn"
      - name: "github"
        field:
          element: "text"
          label: "GitHub"
          help: "Kan vara tom"
          placeholder: "fornamnefternamn"
      - name: "tagline"
        field:
          element: "text"
          label: "Tagline"
          help: "Kort tagline som visas tillsammans med namnet, t.ex. Mobil- och webbutvecklare"
    _posts/blogg:
      - name: "published"
        field:
          element: "checkbox"
          label: "Publicera direkt?"
          value: false
      - name: "heading"
        field:
          element: "text"
          label: "Rubrik"
      - name: "authors"
        field:
          element: "multiselect"
          label: "Författare"
          alterable: false
          options: "http://beta.kits.se/api/prose/medarbetare.jsonp"
      - name: "layout"
        field:
          element: "hidden"
          value: "bloggpost"
      - name: "category"
        field:
          element: "hidden"
          value: "blogg"
    _posts/nyheter:
      - name: "published"
        field:
          element: "checkbox"
          label: "Publicera direkt?"
          value: false
      - name: "heading"
        field:
          element: "text"
          label: "Rubrik"
      - name: "image"
        field:
          element: "text"
          label: "Bild"
          help: "Namnet (utan .jpg) på den bild som ska användas för nyheten (som ska ligga som /images/nyheter/*)"
      - name: "authors"
        field:
          element: "multiselect"
          label: "Författare"
          alterable: false
          options: "http://beta.kits.se/api/prose/medarbetare.jsonp"
      - name: "layout"
        field:
          element: "hidden"
          value: "nyhet"
      - name: "category"
        field:
          element: "hidden"
          value: "nyheter"
    _projekt:
      - name: "heading"
        field:
          element: "text"
          label: "Rubrik"
      - name: "image"
        field:
          element: "text"
          label: "Bild"
          help: "Namnet (utan .jpg) på den bild som ska användas för projektet (som ska ligga som /images/projekt/*)"
      - name: "link"
        field:
          element: "text"
          label: "Länk"
    blogg:
      - name: "layout"
        field:
          element: "hidden"
          value: "blogg"
      - name: "heading"
        field:
          element: "text"
          label: "Rubrik"
      - name: "page_title"
        field:
          element: "text"
          label: "Titel på sidan (om annan än Rubrik)"
      - name: "intro"
        field:
          element: "text"
          label: "Ingress"
      - name: "description"
        field:
          element: "text"
          label: "Text som visas i social medier"
    erbjudanden:
      - name: "layout"
        field:
          element: "hidden"
          value: "erbjudanden"
      - name: "heading"
        field:
          element: "text"
          label: "Rubrik"
      - name: "page_title"
        field:
          element: "text"
          label: "Titel på sidan (om annan än Rubrik)"
      - name: "intro"
        field:
          element: "text"
          label: "Ingress"
      - name: "description"
        field:
          element: "text"
          label: "Text som visas i social medier"
    jobb:
      - name: "layout"
        field:
          element: "hidden"
          value: "jobb"
      - name: "heading"
        field:
          element: "text"
          label: "Rubrik"
      - name: "page_title"
        field:
          element: "text"
          label: "Titel på sidan (om annan än Rubrik)"
      - name: "intro"
        field:
          element: "text"
          label: "Ingress"
      - name: "description"
        field:
          element: "text"
          label: "Text som visas i social medier"
    om:
      - name: "layout"
        field:
          element: "hidden"
          value: "om"
      - name: "heading"
        field:
          element: "text"
          label: "Rubrik"
      - name: "page_title"
        field:
          element: "text"
          label: "Titel på sidan (om annan än Rubrik)"
      - name: "intro"
        field:
          element: "text"
          label: "Ingress"
      - name: "description"
        field:
          element: "text"
          label: "Text som visas i social medier"
