[build]
  command = "npm -v && node -v && find /opt/build/repo && rm -rf /opt/build/repo/node_modules /opt/build/repo/package-lock.json .cache && npm i && npm run build"
  publish = "public"

[[headers]]
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Feature-Policy = "fullscreen 'self'"
