backend:
  name: github
  repo: kits-ab/kits
  branch: main
  squash_merges: true
  commit_messages:
    create: Create {{collection}} "{{slug}}"
    update: Update {{collection}} "{{slug}}"
    delete: Delete {{collection}} "{{slug}}""
    uploadMedia: Upload "{{path}}"
    deleteMedia: Delete "{{path}}"

publish_mode: editorial_workflow

media_folder: static/assets
public_folder: assets

display_url: https://kits.se

slug:
  encoding: ascii
  clean_accents: true

collections:
  - name: blog
    label: Blogg
    folder: content/blogg
    create: true
    delete: false
    extension: md
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "blogg/{{year}}/{{month}}/{{day}}/{{slug}}"
    fields:
      - { name: type, widget: hidden, default: post }
      - { name: title, label: Rubrik }
      - name: authors
        label: Författare
        widget: relation
        collection: persons
        searchFields: [title]
        valueField: id
        displayFields: [title]
        multiple: true
      - { name: body, label: Text, widget: markdown }

  - name: offers
    label: Erbjudanden
    label_singular: Erbjudande
    folder: content/erbjudanden
    create: false
    delete: false
    extension: md
    preview_path: "erbjudanden"
    fields:
      - { name: type, widget: hidden, default: offer }
      - { name: index, widget: hidden }
      - { name: id, widget: hidden }
      - { name: title, label: Rubrik }
      - { name: body, label: Text, widget: markdown }

  - name: benefits
    label: Förmåner
    label_singular: Förmån
    folder: content/formaner
    create: true
    delete: true
    extension: md
    preview_path: "jobb"
    fields:
      - { name: type, widget: hidden, default: benefit }
      - { name: index, label: Sorteringsindex, widget: number, valueType: int, min: 1 }
      - { name: title, label: Rubrik }
      - { name: image, label: Bild, widget: image, required: false, pattern: ["formaner_[a-z-]+\\.jpg", "formaner_[a-z-]+\\.jpg"] }
      - { name: body, label: Text, widget: markdown }

  - name: conferences
    label: Konferenser
    label_singular: Konferens
    folder: content/konferenser
    create: true
    delete: false
    extension: md
    slug: "{{slug}}"
    preview_path: "kitscon/{{slug}}"
    fields:
      - { name: type, widget: hidden, default: conference }
      - { name: id, label: ID }
      - { name: title, label: Rubrik }
      - { name: tagLine, label: Tagline }
      - { name: location, label: Plats }
      - { name: start, label: Startdatum, widget: date, format: "YYYY-MM-DD" }
      - { name: end, label: Slutdatum, widget: date, format: "YYYY-MM-DD" }
      - { name: image, label: Bild, widget: image, required: false }
      - { name: active, label: Visa i listan med Kitscons, widget: boolean, default: false }
      - name: images
        label: Bilder
        widget: list
        required: false
        fields:
          - { name: image, label: Bild, widget: image }
      - name: schema
        label: Schema
        widget: list
        required: false
        fields:
          - { name: title, label: Rubrik }
          - { name: details, label: Detaljer, widget: markdown, required: false }
          - { name: start, label: Starttid, widget: datetime, format: "YYYY-MM-DD HH:mm" }
          - { name: end, label: Sluttid, widget: datetime, format: "YYYY-MM-DD HH:mm" }
          - name: location
            label: Plats
            widget: "object"
            fields:
              - name: coordinates
                label: Koordinater
                widget: list
                hint: "Kommaseparerad, första värdet är latitud and det andra longitur, ex. 57.7001813, 11.9567863"
              - { name: title, label: Namn, required: false }
          - { name: href, label: URL, required: false }
          - name: type
            label: Typ
            widget: select
            options:
              - { label: "Flyg", value: "airplane" }
              - { label: "Båt", value: "boat" }
              - { label: "Buss", value: "bus" }
              - { label: "Check in", value: "checkin" }
              - { label: "Fika", value: "coffee" }
              - { label: "Dricka", value: "drink" }
              - { label: "Mat", value: "food" }
              - { label: "Hotell", value: "hotel" }
              - { label: "Plats", value: "location" }
              - { label: "Presentation", value: "presentation" }
              - { label: "Extern föreläsare", value: "externalpresentation"}
              - { label: "Löpning", value: "running" }
              - { label: "Skidåkning", value: "skiing" }
              - { label: "Workshop", value: "workshop" }
          - name: presenters
            label: Presentatörer
            widget: relation
            collection: persons
            searchFields: [title]
            valueField: id
            displayFields: [title]
            multiple: true
            required: false
          - name: externalpresenter
            label: Extern föreläsare
            widget: "object"
            fields:
              - name: name
                label: Name
                required: true
                widget: string
              - name: href
                label: Länk
                required: false
                widget: string
              - name: avatarSrc
                label: Bild
                required: false
                widget: image
          - { name: presentation, label: Presentation, widget: file, required: false }
          - { name: youtubeId, label: YouTube ID, widget: text, required: false }
          - { name: winner, label: Bästa presentation, widget: boolean, required: false, default: false }
      - { name: body, label: Text, widget: markdown }

  - name: persons
    label: Medarbetare
    folder: content/medarbetare
    create: true
    delete: false
    slug: "{{slug}}"
    fields:
      - { name: type, widget: hidden, default: person }
      - { name: id, label: ID }
      - { name: title, label: Namn }
      - { name: alumni, label: Alumni?, widget: boolean, default: false, required: false }
      - { name: tagLine, label: Tagline }
      - name: image
        label: Bild
        widget: image
        required: false
        pattern: ["medarbetare_[a-z-]+\\.jpg", "medarbetare_[a-z-]+\\.jpg"]
      - name: avatar
        label: Avatar
        widget: image
        required: false
        pattern: ["medarbetare_[a-z-]+-avatar\\.jpg", "medarbetare_[a-z-]+-avatar\\.jpg"]
      - { name: phone, label: Telefon, required: false }
      - { name: email, label: E-mail }
      - name: social
        label: Social
        required: false
        widget: "object"
        fields:
          - { name: github, label: GitHub, required: false }
          - { name: linkedin, label: LinkedIn (hela url:en), required: false }
          - { name: keybase, label: Keybase, required: false }
          - { name: twitter, label: Twitter, required: false }
      - name: tags
        label: Taggar
        widget: list
      - { name: body, label: Body, widget: markdown }

  - name: news
    label: Nyheter
    folder: content/nyheter
    create: true
    delete: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: type, widget: hidden, default: news }
      - { name: title, label: Rubrik }
      - { name: image, label: Bild, widget: image }
      - name: authors
        label: Författare
        widget: relation
        collection: persons
        searchFields: [title]
        valueField: id
        displayFields: [title]
        multiple: true
      - { name: body, label: Body, widget: markdown }

  - name: projects
    label: Projekt
    label_singular: Projekt
    folder: content/projekt
    create: true
    delete: true
    extension: md
    slug: "{{slug}}"
    fields:
      - { name: type, widget: hidden, default: project }
      - { name: index, label: Sorteringsindex, widget: number, valueType: int, min: 1 }
      - { name: title, label: Rubrik }
      - name: image
        label: Bild
        widget: image
        required: false
        pattern: ["projekt_[a-z-]+\\.jpg", "projekt_[a-z]+.jpg"]
      - { name: href, label: Extern länk, required: false }
      - { name: body, label: Text, widget: markdown }

  - name: pages
    label: Sidor
    label_singular: Sida
    folder: content/sidor
    create: false
    delete: false
    extension: md
    fields:
      - { name: type, widget: hidden }
      - { name: title, label: Titel }
      - { name: heading, label: Rubrik }
      - { name: lead, label: Intro, widget: text }
      - name: "section1"
        label: "Sektion 1"
        required: false
        widget: "object"
        fields:
          - { name: subheading, label: Underrubrik, required: false }
          - { name: heading, label: Rubrik, required: false }
          - { name: content, label: Text, widget: text, required: false }
      - name: "section2"
        label: "Sektion 2"
        required: false
        widget: "object"
        fields:
          - { name: subheading, label: Underrubrik, required: false }
          - { name: heading, label: Rubrik, required: false }
          - { name: content, label: Text, widget: text, required: false }
      - name: "section3"
        label: "Sektion 3"
        required: false
        widget: "object"
        fields:
          - { name: subheading, label: Underrubrik, required: false }
          - { name: heading, label: Rubrik, required: false }
          - { name: content, label: Text, widget: text, required: false }
      - name: "section4"
        label: "Sektion 4"
        required: false
        widget: "object"
        fields:
          - { name: subheading, label: Underrubrik, required: false }
          - { name: heading, label: Rubrik, required: false }
          - { name: content, label: Text, widget: text, required: false }
